"""empty message

Revision ID: 0013c251f20a
Revises: ee2ad51bbc34
Create Date: 2024-03-28 16:05:30.346860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013c251f20a'
down_revision = 'ee2ad51bbc34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.Column('n_inicial', sa.Integer(), nullable=False),
    sa.Column('n_final', sa.Integer(), nullable=False),
    sa.Column('cotista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cotista'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talao')
    # ### end Alembic commands ###
