"""empty message

Revision ID: 25ce8bd47576
Revises: 6b322dddb088
Create Date: 2024-03-27 16:23:30.874422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ce8bd47576'
down_revision = '6b322dddb088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifa', schema=None) as batch_op:
        batch_op.drop_column('valor')

    # ### end Alembic commands ###
