"""empty message

Revision ID: 6b322dddb088
Revises: 
Create Date: 2024-02-20 08:23:10.837971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b322dddb088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_tipo_campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criador_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('dt_criacao', sa.DateTime(), nullable=False),
    sa.Column('dt_inicio', sa.Date(), nullable=False),
    sa.Column('dt_fim', sa.Date(), nullable=False),
    sa.Column('meta', sa.Float(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criador_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['dim_tipo_campanha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('disponibilidade', sa.String(length=15), nullable=False),
    sa.Column('dt_compra', sa.DateTime(), nullable=True),
    sa.Column('vendedor', sa.Integer(), nullable=True),
    sa.Column('num_sorteado', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['vendedor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorteio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_campanha', sa.Integer(), nullable=False),
    sa.Column('dt_sorteio', sa.DateTime(), nullable=False),
    sa.Column('id_rifa', sa.Integer(), nullable=False),
    sa.Column('num_sorteado', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('validacao', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['id_campanha'], ['campanha.id'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['id_rifa'], ['rifa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sorteio')
    op.drop_table('rifa')
    op.drop_table('campanha')
    op.drop_table('user')
    op.drop_table('pessoa')
    op.drop_table('dim_tipo_campanha')
    # ### end Alembic commands ###
